modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="playermanagersync"
version="1.0.0"
displayName="PlayerManagerSync NeoForge"
description='Syncs player inventory data for Jexactyl.'
