buildscript {
    repositories {
        maven { url = uri('https://maven.minecraftforge.net') }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.54'
    }
}

plugins {
    id 'java'
}

apply plugin: 'net.minecraftforge.gradle'

group = 'com.urubudpix'
version = '1.0.0'
archivesBaseName = 'playermanagersync-forge'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    version = '1.20.4-45.1.0'
    mappings channel: 'official', version: '1.20.4'
    runs {
        client {
            workingDirectory = file('run')
        }
        server {
            workingDirectory = file('run')
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.4-45.1.0'
}
