plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '1.0.14'
}

group = 'com.urubudpix'
version = '1.0.0'
base.archivesName = 'playermanagersync-neoforge-1.21.1'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.94'

    mods {
        playermanagersync {
            sourceSet project.sourceSets.main
        }
    }
}

dependencies {
}
